from challenge34.unique_charchtares import areCharactersUnique
import pytest

def test_areCharactersUnique():
    with pytest.raises(Exception):
        areCharactersUnique(1)
   
